version: '3.9'

services:
    api:
        image: ailabscomtr/ai-aas-api
        build: ./app
        ports:
            - "8000:80"

    redis:
        image: redis:5.0.12-alpine
        volumes:
            - ai-aas-redis-data:/data
        #command: redis-server --apendonly
        
    milvus:
        image: milvusdb/milvus:1.1.0-cpu-d050721-5e559c
        volumes:
            - ai-aas-milvus-db:/var/lib/milvus/db
            - ./milvus-conf:/var/lib/milvus/conf
            - ai-aas-milvus-logs:/var/lib/milvus/logs
            - ai-aas-milvus-wal:/var/lib/milvus/wal

    zsl:
        image: ailabscomtr/zsl
        build: ./zsl
        profiles:
            - all
            - zsl
            - turkish

    qaqg:
        image: ailabscomtr/ai-aas-qaqg
        build: ./qaqg
        profiles:
            - all
            - qaqg
            - turkish

    ats:
        image: ailabscomtr/ai-aas-ats
        build: ./ats
        profiles:
            - all
            - ats
            - turkish

    ner:
        image: ailabscomtr/ai-aas-ner
        build: ./ner
        profiles:
            - all
            - ner
            - turkish


volumes:
    ai-aas-redis-data:
    ai-aas-milvus-db:
    ai-aas-milvus-logs:
    ai-aas-milvus-wal:

       