version: '3.9'

services:
    api:
        build: ./app
        ports:
            - "8000:80"

    zsl:
        build: ./zsl
        profiles:
            - all
            - zsl

    redis:
        image: redis:5.0.12-alpine
        volumes:
            - /etc/data/redis:/data
        #command: redis-server --apendonly